### ISSUE TITLE
Erro ao exibir os nomes das cartas

### ISSUE THREAD

**Issue by devnetgomez** [joelgarciajr84/br-pilot-android-app#1]
@joelgarciajr84  Quando escolhemos o tipo de carta VAC, a lista é carregada mas não mostra os nomes, apenas os ícones. Ao usar o botão de download, é carregado um documento de carta revogada.

![screenshot 16 de jul de 2016 09-39-27](https://cloud.githubusercontent.com/assets/810723/16894815/529730ce-4b39-11e6-8793-24a44b750ff8.png)

**Comment by joelgarciajr84** [comment]
Corrigido em https://github.com/joelgarciajr84/br-pilot-android-app/commit/57330d972e1396af6eed2a3a6c87e43173785ef6
