### ISSUE TITLE
Criar tela de Informações sobre o aplicativo

### ISSUE THREAD

**Issue by devnetgomez** [joelgarciajr84/br-pilot-android-app#2]
Seria ideal ter uma tela onde as pessoas pudessem ver informação do desenvolvedor e a origem dos dados apresentados no app.

**Comment by joelgarciajr84** [comment]
Estou desenvolvendo essa funcionalidade junto com a feature de favoritos

**Comment by joelgarciajr84** [comment]
Corrigido em https://github.com/joelgarciajr84/br-pilot-android-app/commit/57330d972e1396af6eed2a3a6c87e43173785ef6
